import type { Ticket, Persona, Project } from "@/types";

export const personas: Persona[] = [
  {
    id: "p1", name: "Kira", slug: "kira", color: "#3b82f6",
    role: "developer",
    personality: "Methodical and precise. Prefers small, well-tested PRs over large sweeping changes.",
    skills: ["React", "TypeScript", "Node.js", "Testing", "CI/CD"],
    processes: ["TDD", "Code review", "Trunk-based dev"],
    goals: ["Clean code", "Test coverage", "Ship fast"],
    permissions: { tools: ["git", "npm", "docker", "bash"], folders: ["src/", "tests/"] },
  },
  {
    id: "p2", name: "Renzo", slug: "renzo", color: "#22c55e",
    role: "lead",
    personality: "Calm under pressure. Breaks big goals into achievable sprints.",
    skills: ["Planning", "Risk assessment", "Agile", "Sprint planning"],
    processes: ["Stand-ups", "Retrospectives", "Status reports"],
    goals: ["On-time delivery", "Team velocity", "Clear priorities"],
    permissions: { tools: ["tickets", "calendar", "notifications"], folders: ["docs/", "plans/"] },
  },
  {
    id: "p3", name: "Mika", slug: "mika", color: "#f59e0b",
    role: "designer",
    personality: "Visually driven with strong opinions about whitespace.",
    skills: ["Figma", "UI design", "UX research", "Design systems", "Accessibility"],
    processes: ["User interviews", "Design critique", "Iterative prototyping"],
    goals: ["User satisfaction", "Consistent design", "Accessible interfaces"],
    permissions: { tools: ["figma", "image-gen", "file-read"], folders: ["assets/", "components/"] },
  },
];

export const project: Project = {
  id: "proj1",
  name: "Bonsai",
  slug: "bonsai",
  ticketCount: 14,
};

export const tickets: Ticket[] = [
  {
    id: 1,
    title: "Design System Foundation",
    description:
      "Create base color tokens, typography scale, and spacing system for the Bonsai UI. Establish dark theme as default.",
    type: "feature",
    state: "shipped",
    priority: 900,
    assignee: personas[0],
    commentCount: 3,
    hasAttachments: false,
    lastAgentActivity: "2h ago",
    createdAt: "2026-01-28",
  },
  {
    id: 2,
    title: "Project Board Kanban View",
    description:
      "Build the main kanban board with drag-and-drop columns for ticket states. Support filtering by type and assignee.",
    type: "feature",
    state: "building",
    priority: 1000,
    assignee: personas[0],
    commentCount: 5,
    hasAttachments: true,
    lastAgentActivity: "12m ago",
    createdAt: "2026-01-30",
  },
  {
    id: 3,
    title: "Heartbeat Service Integration",
    description:
      "Connect the webapp to the heartbeat status API. Show agent activity, queue depth, and last run time on the dashboard.",
    type: "feature",
    state: "planning",
    priority: 800,
    assignee: personas[1],
    commentCount: 2,
    hasAttachments: false,
    lastAgentActivity: "1h ago",
    createdAt: "2026-01-31",
  },
  {
    id: 4,
    title: "Ticket Detail View",
    description:
      "Full ticket detail page with description, acceptance criteria, comment thread, and agent activity log.",
    type: "feature",
    state: "planning",
    priority: 700,
    commentCount: 0,
    hasAttachments: false,
    createdAt: "2026-02-01",
  },
  {
    id: 5,
    title: "Agent Persona Configuration",
    description:
      "Settings page for managing agent personas — name, color, avatar, and default tool profile.",
    type: "feature",
    state: "planning",
    priority: 500,
    commentCount: 1,
    hasAttachments: false,
    createdAt: "2026-02-01",
  },
  {
    id: 6,
    title: "Fix Column Overflow on Small Screens",
    description:
      "Board columns overflow horizontally without scroll indicators on viewports below 1280px.",
    type: "bug",
    state: "planning",
    priority: 600,
    commentCount: 0,
    hasAttachments: false,
    createdAt: "2026-02-02",
  },
  {
    id: 7,
    title: "SQLite Database Schema",
    description:
      "Set up Prisma with SQLite. Create models for Project, Ticket, Comment, Document, AgentRun, and Persona.",
    type: "feature",
    state: "planning",
    priority: 850,
    assignee: personas[2],
    commentCount: 4,
    hasAttachments: true,
    lastAgentActivity: "35m ago",
    createdAt: "2026-01-29",
  },
  {
    id: 8,
    title: "Comment Thread Component",
    description:
      "Threaded comment UI for ticket detail view. Support human and agent comments with different styling.",
    type: "feature",
    state: "planning",
    priority: 650,
    commentCount: 0,
    hasAttachments: false,
    createdAt: "2026-02-02",
  },
  {
    id: 9,
    title: "Startup Token Auth",
    description:
      "Implement Jupyter-style token auth. Generate token on first run, validate via cookie and Authorization header.",
    type: "feature",
    state: "test",
    priority: 950,
    assignee: personas[1],
    commentCount: 7,
    hasAttachments: false,
    lastAgentActivity: "45m ago",
    createdAt: "2026-01-28",
  },
  {
    id: 10,
    title: "Onboarding Wizard Flow",
    description:
      "First-run setup wizard: API key entry, project creation, heartbeat service install, vault initialization.",
    type: "feature",
    state: "planning",
    priority: 750,
    assignee: personas[0],
    commentCount: 3,
    hasAttachments: false,
    lastAgentActivity: "3h ago",
    createdAt: "2026-02-01",
  },
  {
    id: 11,
    title: "Git Operations Module",
    description:
      "Implement clone, branch, commit, push operations for agent workspaces. Validate paths and prevent escapes.",
    type: "feature",
    state: "building",
    priority: 900,
    assignee: personas[2],
    commentCount: 6,
    hasAttachments: true,
    lastAgentActivity: "8m ago",
    createdAt: "2026-01-30",
  },
  {
    id: 12,
    title: "Clean Up Stale Agent Locks",
    description:
      "Add automated cleanup of agent locks older than 45 minutes. Prevent stuck tickets after heartbeat crashes.",
    type: "chore",
    state: "test",
    priority: 800,
    assignee: personas[2],
    commentCount: 2,
    hasAttachments: false,
    lastAgentActivity: "1h ago",
    createdAt: "2026-02-03",
  },
  {
    id: 13,
    title: "Ticket State Transition Validation",
    description:
      "Enforce valid state transitions. Backlog can only move to Research, Research to Ready, etc.",
    type: "chore",
    state: "building",
    priority: 700,
    assignee: personas[1],
    commentCount: 1,
    hasAttachments: false,
    lastAgentActivity: "2h ago",
    createdAt: "2026-02-03",
  },
  {
    id: 14,
    title: "Sidebar Navigation with Active States",
    description:
      "Icon-based sidebar with hover tooltips and active route highlighting. Include home, board, projects, settings.",
    type: "feature",
    state: "shipped",
    priority: 850,
    assignee: personas[0],
    commentCount: 2,
    hasAttachments: false,
    lastAgentActivity: "5h ago",
    createdAt: "2026-01-29",
  },
];
